name: iOS CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on macOS
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build iOS App
        run: |
          xcodebuild clean build \
            -project HelloCI.xcodeproj \
            -scheme HelloCI \
            -destination 'platform=iOS Simulator,name=iPhone 14'