name: iOS CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-14   # Use a modern runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List installed Xcode versions
        run: ls /Applications | grep Xcode

      - name: Build iOS App
        run: |
          xcodebuild clean build \
            -project HelloCI.xcodeproj \
            -scheme HelloCI \
            -destination 'platform=iOS Simulator,name=iPhone 14'