name: iOS CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build iOS App
        run: |
          xcodebuild clean build \
            -project HelloCI.xcodeproj \
            -scheme HelloCI \
            -destination 'platform=iOS Simulator,name=iPhone 14'